/*
 * The Czech words the calendar grid adds.
 *
 * Kept beside the grid rather than in `cs.json` because three teams change
 * the calendar screens at once tonight and the locale file is the one place
 * all three would touch; a module of their own keeps the merge clean. Moving
 * them into `cs.json` later is a mechanical change.
 */
export const GRID_TEXT = {
  book: 'Objednat',
  block: 'Zablokovat',
  blockTitle: 'Zablokovat čas',
  blockReason: 'Důvod blokace',
  blockReasonHelp: 'Zobrazí se v kalendáři u zablokovaného času.',
  blocked: 'Blokováno',
  blockDetailTitle: 'Zablokovaný čas',
  unblock: 'Zrušit blokaci',
  unblockConfirm: 'Blokace se zruší a čas bude znovu volný k objednání.',
  cancel: 'Zpět',
  close: 'Zavřít',
  newBooking: 'Nové objednání',
  publicHoliday: 'Státní svátek',
  holidayWorked: 'Svátek – pracuje se',
  closed: 'Zavřeno',
  notAWorkingDay: 'Nepracovní den',
  lunchBreak: 'Oběd',
  noPeriod: 'Mimo období',
  noActivities: 'Bez činností',
  onlineBookingOff: 'Online objednávky vypnuty',
  onlineBookingOffWhy:
    'Pacienti se teď nemohou objednat přes web. Zapíná se v Nastavení → Veřejný web a kontakty.',
  view: 'Zobrazení',
  calendars: 'Kalendáře',
  onlyThis: 'Zobrazit jen tento kalendář',
  employees: 'Pracovníci v zobrazeném období',
  noEmployees: 'V zobrazeném období není nikdo rozepsaný.',
  allEmployees: 'Všichni pracovníci',
  employee: 'Pracovník',
  services: 'Služby',
  allServices: 'Všechny služby',
  service: 'Služba',
  jumpTo: 'Přejít na datum',
  otherWorker: 'jiný pracovník',

  /* The board's chrome (3. 10. 2026). */
  today: 'Dnes',
  previous: 'Předchozí',
  next: 'Další',
  dayView: 'Den',
  weekView: 'Týden',
  monthView: 'Měsíc',
  newAppointment: 'Nová objednávka',
  resolution: 'Rozlišení',
  coarser: 'Hrubší mřížka',
  finer: 'Jemnější mřížka',
  gridStepHint: (step: string) => `Krok mřížky ${step} · táhněte do stran pro posun v čase`,
  scrollLeft: 'Posunout doleva',
  scrollRight: 'Posunout doprava',
  todayPill: 'DNES',
  holidayPill: 'SVÁTEK',
  closedCaps: 'ZAVŘENO',
  holidayClosed: 'Státní svátek — zavřeno',
  vacation: 'Dovolená',
  absence: 'Nepřítomnost',
  more: (count: number) => `+ ${count} další`,
  bookPatient: 'Objednat pacienta',
  bookPatientHint: 'Vyhledat nebo rychle založit',
  blockTime: 'Zablokovat čas',
  blockTimeHint: 'Pauza, dovolená, školení',
  cancelSelection: 'Zrušit výběr',
  escape: 'Esc',
  legendSelecting: 'Právě vybíráte',
  legendBooked: 'Obsazeno',
  legendBlocked: 'Zablokováno',
  legendHoliday: 'Svátek',
  legendNow: 'Aktuální čas',
  clubLine: 'Klub',
  clubBlock: 'Blok klubu',
  afternoonFree: 'odpoledne volno',
} as const;
